export default {
  forcedWinner: 'John Doe',
  theme: {
    appLogoImgSrc: '/images/raffle-logo.jpg',
    bgColor: '#F7F7F7',
    buttonColor: '#FF070C',
    listItemBgColorEven: '#E7EDED',
    textColor: '#000834',
  },
  text: {
    addParticipantsTitle: 'Add Participants',
    backButton: 'Go Back',
    cancelButton: 'Cancel',
    confirmButton: 'Confirm & Go!',
    confirmTitle: 'Confirm the participants',
    congratulationsSuperTitle: 'Congratulations!',
    congratulationsTitle: 'The winner is...',
    continueButton: 'Continue',
    enterButton: 'Enter now!',
    finishButton: 'Finalize',
    pickingWinnerTitle: 'Picking the winner',
    slogan: 'Win prizes today, good luck.',
    startOverButton: 'Start Over',
  },
};
